* proxy-ns
=proxy-ns= is a Linux-specific command-line tool that can force any
program to use your SOCKS5 proxy server.

** Features
It has several advantages over =proxychains=:
- Support both TCP and UDP
- Work for statically linked programs

** Installation
*** Arch Linux
=proxy-ns= is available at [[https://aur.archlinux.org/packages/proxy-ns][AUR]].
*** Other
You can manually clone this repository, then use =make install=.
#+begin_src sh
  git clone https://github.com/OkamiW/proxy-ns.git
  cd proxy-ns
  make && sudo make install
#+end_src

** Configuration
First, generate your configuration file:
#+begin_src sh
  proxy-ns -g
#+end_src

By default, =proxy-ns= uses the configuration file at
=$XDG_CONFIG_HOME/proxy-ns/config.json=. In case =XDG_CONFIG_HOME= is
not set, it would be =$HOME/.config/proxy-ns/config.json=.

Here's the default configuration file:
#+begin_src js-json
  {
    "tun_name": "tun0",
    "tun_ip": "10.0.0.1/24",
    "socks5_address": "127.0.0.1:1080",
    "fake_dns": true,
    "fake_network": "240.0.0.0/4",
    "dns_server": "9.9.9.9"
  }
#+end_src
Normally, you only need to change =socks5_address=.

** Notes about FakeDNS
FakeDNS can be used to avoid a separate DNS roundtrip, thus improving
latency. But it has its own limitations:
- All domains are resolved to =fake_network=, some programs may not
  work as expected(e.g. =geoiplookup=).
- Some programs may not use your system DNS resolver. FakeDNS won't
  work for them.

** FAQ
*** Why can't I ping as a normal user inside =proxy-ns=?
Because =proxy-ns= creates a new network namespace.

For many distributions, =/proc/sys/net/ipv4/ping_group_range= defaults
to =1 0= in a new network namespace, which disallows ping for all groups.

Since SOCKS5 doesn't support ICMP, it would be pointless to =ping=
inside =proxy-ns= anyway.
*** My program cannot resolve any domain
Your SOCKS5 server may not support the /UDP ASSOCIATE/ command.

Usually, you can work around this by enabling =fake_dns= (it's enabled
by default).

However, some programs resolve domains themselves. You will need to
enable UDP support on your proxy server for these programs to function
properly.
